### ISSUE TITLE
Improve your website

### ISSUE THREAD

**Issue by samhwang** [masd1234/masd1234.github.io#1]
Hey Marco,

I just came across [your post in the Codecademy Community fb group](https://www.facebook.com/groups/codecademy.community/?post_id=652621872063711), and want to give some feedback on your site.

Overall, the page looks nice. But there are definitely a few points that can be improved.

## Typos

When referring to tech stuff as initials, write them in ALL CAPS, or at least use the CORRECT initials. For example:

- `Html` => `HTML`
- `Css` => `CSS`
- `Sql` => `SQL`
- `Saas` => I think you meant `Sass` ?
  [`SaaS`](https://en.wikipedia.org/wiki/Software_as_a_service) and [`Sass`](https://sass-lang.com/) are very different things. Look it up to see which one you want to use.
- `Javascritp`, `Javascript` => Should be `JavaScript` or just `JS`. People will understand what `JS` is.

Other typo and spelling related stuff:

- `jQuery` and `Git` is fine the way it is.
- It's "GitHub", not "Git Hub"
- It's "LinkedIn", not "Linked In"
- "web-aplications" should be "web applications"
- "web-pages" should just be "web pages". Or you can use the word "websites". Sounds better ?
- "beatifull" => "beautiful"
  
Another touch on wording and grammar:

- "...always looking forward for new challenges and learn new things." should be "...always looking forward ~for~ **to** new challenges and learn**ing** new things".
- "builded" => "built"
- "builded using" => "built with"
- "dowload my resume:" => "Download my resume"

Overall, a lot of these can be avoid/mitigated by using a spelling/grammar checker.

## Page Title

- The HTML Title of your page is called "Document". Surely, you will want to change this into something else.
  Not only because it looks very "unprofessional" _(but you're learning, so it's OK!)_, it will also hurt your SEO in the
  long run, if you ever plan on doing that.
  This could be your name "Marco Sanchez", or "Marco's Personal website", "Marco's Portfolio", and so on.

As a HTML title, it will show up here.
![Screen Shot 2020-08-30 at 1 08 59 pm](https://user-images.githubusercontent.com/4188758/91650552-6b207400-eac4-11ea-8b6f-abba39d2e7a0.png)

## FontAwesome Icons
![Screen Shot 2020-08-30 at 1 31 48 pm](https://user-images.githubusercontent.com/4188758/91650624-3365fc00-eac5-11ea-9e3d-dca8fb27d853.png)

Seriously, though. They are going to release FA 6 anytime soon, so I don't really understand why your site is still using FA 4.

![Screen Shot 2020-08-30 at 1 31 55 pm](https://user-images.githubusercontent.com/4188758/91650626-39f47380-eac5-11ea-8073-4a6371d0829b.png)

## Page Header Menu

- The size of your menu looks ok on Desktop screens. But it takes way too much space in Mobile mode.
- `<li>` tag should go on the outside of `<a>`, not the other way around. Because the direct children
  of the `<ul>` element is the `<li>`, not `<a>`
- The spacing of your "[Icon] [MenuName]" is not very responsive friendly.
![Screen Shot 2020-08-30 at 1 08 24 pm](https://user-images.githubusercontent.com/4188758/91650548-5b089480-eac4-11ea-96a5-a1bc061cb4b9.png)
  
I'd suggest you split this block into 2 divs, 1 div for the Icon and 1 div for the menu name.

So this can probably be like this:
  
```HTML
<li class="li">
  <a href="#home">
    <div class="menu-icon">
      <i class="fas fa-home" />
    </div>
    <div class="menu-text">
      Home
    </div>
  </a>
</li>
```

## Project Showcase

- Try to think of something creative to say for the Mundostar, Colomar and Vu projects. Maybe saying
  the theme is for "whatever-kind-of-business" that can use this template. Don't just put "A beautiful
  and responsive web page" as a description.
- Don't put MP4s as a demo, because it can stop, and it will stop. The better way to handle this is
  using a GIF, so that it loops itself going on forever.
- Don't put underlines in the project titles. In a UX point of view, an underline usually means that
  it is a clickable URL, while your project titles are just text and not an URL.
- The "Showcase" blocks styling is not very consistent. See Screenshot for what I mean.

![Screen Shot 2020-08-30 at 1 22 17 pm](https://user-images.githubusercontent.com/4188758/91650564-89866f80-eac4-11ea-928d-109b52270b62.png)
![Screen Shot 2020-08-30 at 1 22 11 pm](https://user-images.githubusercontent.com/4188758/91650560-85f2e880-eac4-11ea-94f0-667dfc854e07.png)

## Tech Stack Icons

- Some of the icons looks super stretched in a very weird dimension, plus the size is not consistent.
  Try to crop the images into a square, and convert/compress them into the same size before uploading.
- The "SQL" icon is not even transparent, you can clearly see the mesh background.

![Screen Shot 2020-08-30 at 1 23 12 pm](https://user-images.githubusercontent.com/4188758/91650570-973bf500-eac4-11ea-974f-ff562e3f2296.png)

**Comment by masd1234** [comment]
Hi Sam,


Thank you so much for your feedback, I am making the changes now.



Thank you so much again.


Best regards.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
